// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATviA3cwBIeC2B3kYllaJhx17ahpTb9nk',
    appId: '1:591783490081:web:7fc48040c51c6c6e27e960',
    messagingSenderId: '591783490081',
    projectId: 'smartlife2-3c3b4',
    authDomain: 'smartlife2-3c3b4.firebaseapp.com',
    databaseURL: 'https://smartlife2-3c3b4-default-rtdb.firebaseio.com',
    storageBucket: 'smartlife2-3c3b4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgMjxy3HIAu9T_Q67J_mlrpj8YSKv05T4',
    appId: '1:591783490081:android:c48903ee849d75fd27e960',
    messagingSenderId: '591783490081',
    projectId: 'smartlife2-3c3b4',
    databaseURL: 'https://smartlife2-3c3b4-default-rtdb.firebaseio.com',
    storageBucket: 'smartlife2-3c3b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArTPWY7oQKz5Q7XtSRvGGROo6vDs3QbVY',
    appId: '1:591783490081:ios:e664e438c4ffe78227e960',
    messagingSenderId: '591783490081',
    projectId: 'smartlife2-3c3b4',
    databaseURL: 'https://smartlife2-3c3b4-default-rtdb.firebaseio.com',
    storageBucket: 'smartlife2-3c3b4.appspot.com',
    iosClientId: '591783490081-j68d9vrkt2qvs594bo8pk8vaka3h1ac8.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartlife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArTPWY7oQKz5Q7XtSRvGGROo6vDs3QbVY',
    appId: '1:591783490081:ios:e664e438c4ffe78227e960',
    messagingSenderId: '591783490081',
    projectId: 'smartlife2-3c3b4',
    databaseURL: 'https://smartlife2-3c3b4-default-rtdb.firebaseio.com',
    storageBucket: 'smartlife2-3c3b4.appspot.com',
    iosClientId: '591783490081-j68d9vrkt2qvs594bo8pk8vaka3h1ac8.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartlife',
  );
}
